extends: airbnb
parser: "babel-eslint"
env:
  browser: true
  es6: true
  mocha: true
  node: true
plugins:
  - react
  - jsx-a11y
  - import
rules:
  eol-last: "off"
  semi: ["error", "never"]
  class-methods-use-this: "off"
  no-confusing-arrow: "off"
  no-plusplus: "off"
  arrow-parens: ["error", "as-needed"]
  max-len: ["error", 150]
  newline-per-chained-call: ["error", { "ignoreChainWithDepth": 5 }]
  func-names: ["error", "never"]
  comma-dangle: ["error", {
    "arrays": "never",
    "objects": "never",
    "imports": "never",
    "exports": "never",
    "functions": "ignore",
  }]
  react/jsx-filename-extension: ["warn", { "extensions": [".js", ".jsx"] }]
  react/prefer-stateless-function: "off"
  react/require-extension: "off"
  jsx-a11y/no-static-element-interactions: "off"
  import/prefer-default-export: "off"